// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Retailer_Winning_Formula.DataLayer.Entities
{
    public partial class Address
    {
        public Address()
        {
            EntityAddress = new HashSet<EntityAddress>();
            PreferredAddress = new HashSet<PreferredAddress>();
        }

        public long Id { get; set; }
        public int AddressTypeId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public int? CountryId { get; set; }
        public short? TimeZoneId { get; set; }

        public virtual AddressType AddressType { get; set; }
        public virtual ICollection<EntityAddress> EntityAddress { get; set; }
        public virtual ICollection<PreferredAddress> PreferredAddress { get; set; }
    }
}