// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Retailer_Winning_Formula.DataLayer.Entities
{
    public partial class BamboraProfile
    {
        public long Id { get; set; }
        public DateTime CcexpDate { get; set; }
        public string BamboraProfileId { get; set; }
    }
}