// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Retailer_Winning_Formula.DataLayer.Entities
{
    public partial class Batch
    {
        public int Id { get; set; }
        public string Source { get; set; }
        public int NumberOfCodes { get; set; }
        public DateTime BatchCreationDate { get; set; }
    }
}