// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Retailer_Winning_Formula.DataLayer.Entities
{
    public partial class Bundle
    {
        public long Id { get; set; }
        public DateTime StartDate { get; set; }
        public decimal Price { get; set; }
        public decimal Discount { get; set; }
        public DateTime? EndDate { get; set; }
    }
}