// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Retailer_Winning_Formula.DataLayer.Entities
{
    public partial class EmailAddress
    {
        public EmailAddress()
        {
            EntityEmailAddress = new HashSet<EntityEmailAddress>();
            PreferredEmailAddress = new HashSet<PreferredEmailAddress>();
        }

        public long Id { get; set; }
        public string EmailAddress1 { get; set; }
        public bool? IsVerified { get; set; }

        public virtual ICollection<EntityEmailAddress> EntityEmailAddress { get; set; }
        public virtual ICollection<PreferredEmailAddress> PreferredEmailAddress { get; set; }
    }
}