// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Retailer_Winning_Formula.DataLayer.Entities
{
    public partial class MarketPartner
    {
        public long Id { get; set; }
        public string Dbaname { get; set; }
        public string LegalName { get; set; }
        public string RetailerCode { get; set; }
        public string TaxNumber { get; set; }
        public int? LanguageId { get; set; }
        public int? BuyingGroupId { get; set; }
        public short? CurrencyId { get; set; }
        public int? Asvid { get; set; }
    }
}