// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Retailer_Winning_Formula.DataLayer.Entities
{
    public partial class MpbankingDetail
    {
        public long Id { get; set; }
        public long MarketPartnerId { get; set; }
        public int TransitNum { get; set; }
        public int InstitutionNum { get; set; }
        public long? AccountNum { get; set; }
    }
}