// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Retailer_Winning_Formula.DataLayer.Entities
{
    public partial class PhoneNumber
    {
        public PhoneNumber()
        {
            EntityPhoneNumber = new HashSet<EntityPhoneNumber>();
            PreferredPhoneNumber = new HashSet<PreferredPhoneNumber>();
        }

        public long Id { get; set; }
        public int PhoneNumberTypeId { get; set; }
        public long PhoneNumber1 { get; set; }

        public virtual PhoneNumberType PhoneNumberType { get; set; }
        public virtual ICollection<EntityPhoneNumber> EntityPhoneNumber { get; set; }
        public virtual ICollection<PreferredPhoneNumber> PreferredPhoneNumber { get; set; }
    }
}