// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Retailer_Winning_Formula.DataLayer.Entities
{
    public partial class PhoneNumberType
    {
        public PhoneNumberType()
        {
            PhoneNumber = new HashSet<PhoneNumber>();
        }

        public int Id { get; set; }
        public string Represents { get; set; }

        public virtual ICollection<PhoneNumber> PhoneNumber { get; set; }
    }
}