// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Retailer_Winning_Formula.DataLayer.Entities
{
    public partial class PlanPricingData
    {
        public int Id { get; set; }
        public int? PlanId { get; set; }
        public string PlanType { get; set; }
        public decimal? PlanCost { get; set; }
        public string ComboType { get; set; }
        public decimal? ComboAddonCost { get; set; }
        public decimal? ComboAddonDiscount { get; set; }
        public string ComboAlternateType { get; set; }
        public decimal? ComboAlternateAddonCost { get; set; }
        public decimal? ComboAlternateAddonDiscount { get; set; }
        public decimal? ComboAllThreeAddonCost { get; set; }
        public decimal? ComboAllThreeDiscount { get; set; }
    }
}