// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Retailer_Winning_Formula.DataLayer.Entities
{
    public partial class PlanImages
    {
        public int PlanSumId { get; set; }
        public string Plans { get; set; }
        public string ImageLink { get; set; }
    }
}