// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Retailer_Winning_Formula.DataLayer.Entities
{
    public partial class SessionData
    {
        public long Id { get; set; }
        public Guid? WebLinkGuid { get; set; }
        public short? GiftCardValue { get; set; }
        public string ChosenPlans { get; set; }
    }
}