// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Retailer_Winning_Formula.DataLayer.Entities
{
    public partial class SmartOneActivation
    {
        public long Id { get; set; }
        public int PlanId { get; set; }
        public string Code { get; set; }
        public DateTime CreationDate { get; set; }
        public string CompleteValue { get; set; }
        public DateTime? ActivationDate { get; set; }
        public string MarketPartnerReceipt { get; set; }
        public long? MarketPartnerId { get; set; }
        public long? EntityId { get; set; }
    }
}