// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Retailer_Winning_Formula.DataLayer.Entities
{
    public partial class UserReports
    {
        public Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Store { get; set; }
        public string Location { get; set; }
        public bool IsProductProtectionPlanOffered { get; set; }
        public decimal AnnualSalesVolume { get; set; }
        public decimal PercentageOfRevenuePlanSales { get; set; }
        public decimal SalesAssociateCommission { get; set; }
        public decimal SlpPotentialEnrolments { get; set; }
        public decimal AvgMonthlyRetailValue { get; set; }
        public decimal AvgTicketValue { get; set; }
        public string DefaultFactors { get; set; }
        public decimal Year1NetSmartOneRevenue { get; set; }
        public decimal Year1SmarterLivingRecuringRevenue { get; set; }
        public decimal Year1TotalRevenue { get; set; }
        public decimal Year1MultipleTimesImprovementWithSlp { get; set; }
        public decimal Year2NetSmartOneRevenue { get; set; }
        public decimal Year2SmarterLivingRecuringRevenue { get; set; }
        public decimal Year2TotalRevenue { get; set; }
        public decimal Year2MultipleTimesImprovementWithSlp { get; set; }
        public decimal Year3NetSmartOneRevenue { get; set; }
        public decimal Year3SmarterLivingRecuringRevenue { get; set; }
        public decimal Year3TotalRevenue { get; set; }
        public decimal Year3MultipleTimesImprovementWithSlp { get; set; }
        public decimal Year4NetSmartOneRevenue { get; set; }
        public decimal Year4SmarterLivingRecuringRevenue { get; set; }
        public decimal Year4TotalRevenue { get; set; }
        public decimal Year4MultipleTimesImprovementWithSlp { get; set; }
        public decimal Year5NetSmartOneRevenue { get; set; }
        public decimal Year5SmarterLivingRecuringRevenue { get; set; }
        public decimal Year5TotalRevenue { get; set; }
        public decimal Year5MultipleTimesImprovementWithSlp { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}